import {
  PACKAGING_WORKFLOW_PATH,
  type PackagingCheck,
  type PackagingCheckKind,
  type PackagingPlan,
} from '@orchestra/contracts';

const stepForKind: Record<PackagingCheckKind, { name: string; run: string }> = {
  docker_build: {
    name: 'Build preview image',
    run: 'docker build -f Dockerfile -t orchestra-iteration-packaging:$GITHUB_SHA .',
  },
  container_health: {
    name: 'Verify container health',
    run: [
      'docker run -d --name orchestra-packaging-health -p 8080:8080 orchestra-iteration-packaging:$GITHUB_SHA',
      'for i in 1 2 3 4 5 6 7 8 9 10; do',
      '  if curl -fsS http://127.0.0.1:8080/health >/dev/null; then exit 0; fi',
      '  sleep 2',
      'done',
      'docker logs orchestra-packaging-health || true',
      'exit 1',
    ].join('\n'),
  },
  unit_tests: {
    name: 'Run unit tests',
    run: [
      'if [ -f pnpm-lock.yaml ]; then',
      '  corepack enable',
      '  pnpm test',
      'elif [ -f yarn.lock ]; then',
      '  yarn test',
      'elif [ -f package-lock.json ] || [ -f package.json ]; then',
      '  npm test',
      'else',
      '  echo "No supported package manager lockfile for unit_tests"',
      '  exit 1',
      'fi',
    ].join('\n'),
  },
};

/**
 * Fixed Forgejo Actions workflow rendered from a structured packaging plan.
 * Trigger is workflow_dispatch only: this stack has no Actions runner, and
 * push-triggered runs would sit Waiting then get cancelled on every Builder
 * commit. Orchestra executes the mirrored checks in preview-manager and posts
 * orchestra/packaging/* commit statuses as the handoff green light.
 */
export function renderPackagingWorkflow(plan: PackagingPlan): string {
  const jobs = plan.checks.map((check) => renderCheckJob(check)).join('\n');
  return [
    '# Generated by Orchestra from the Planner packaging-plan.',
    '# Do not edit by hand; agents cannot author workflow YAML.',
    '# Execution green light comes from Orchestra packaging sandbox statuses',
    '# (orchestra/packaging/*), not from an Actions runner in this milestone.',
    'name: Iteration packaging',
    'on:',
    '  workflow_dispatch:',
    'jobs:',
    jobs,
    '',
  ].join('\n');
}

function renderCheckJob(check: PackagingCheck): string {
  const step = stepForKind[check.kind];
  const continueOnError = check.required ? 'false' : 'true';
  const runLines = step.run.split('\n').map((line) => `          ${line}`).join('\n');
  return [
    `  ${check.id}:`,
    `    name: ${step.name}`,
    '    runs-on: ubuntu-latest',
    '    steps:',
    '      - uses: actions/checkout@v4',
    `      - name: ${step.name}`,
    `        continue-on-error: ${continueOnError}`,
    '        run: |',
    runLines,
  ].join('\n');
}

export function packagingWorkflowPath(): string {
  return PACKAGING_WORKFLOW_PATH;
}
